### ISSUE TITLE
State problem

### ISSUE THREAD

**Issue by MohamadFikryAzhar** [maulanazn/hirejob-fe#1]
Login and register page cannot defined state from reducers

**Comment by maulanazn** [comment]
Please push your code and show me the code you meet with the error.

**Comment by MohamadFikryAzhar** [comment]
Code have been pushed in fe/authorization branch
The code i met with the error is in
pages/auth/candidate/login.jsx:16
pages/auth/candidate/register.jsx:15
pages/auth/recruiter/login.jsx:16
pages/auth/recruiter/register.jsx:15
I've also some state codes attached here:
![image](https://github.com/maulanazn/hirejob-fe/assets/136974445/55fd7299-546a-4f63-b3d0-f668b1eef38f)
![image](https://github.com/maulanazn/hirejob-fe/assets/136974445/297dc707-8128-4da9-bdb8-cd428acc34a7)
![image](https://github.com/maulanazn/hirejob-fe/assets/136974445/139a6896-620d-4e6c-8126-c44cc82c62c2)
![image](https://github.com/maulanazn/hirejob-fe/assets/136974445/e9b5a7df-7fc5-430f-900d-630ef79fa463)

**Comment by maulanazn** [comment]
try use direct reducers combination, such as loginrecruiter: examplereducers, registerrecruiter: exampleReducers, and so on. Not like candidate: {login: examplereducers}

**Comment by MohamadFikryAzhar** [comment]
Thanks for the advice
